default:
  permissions:
    group.default: true
    permissions.build: false
    command.join.to: true
    command.join.from: true
    minecraft.autocraft: true
  worlds:
    custom:
      permissions.build: true
      command.join.to: false
      command.hoops: true
      command.charades: true
      command.7: true
    outworld:
      command.join.to: false
      command.join.from: false
    outworld_nether:
      command.join.to: false
      command.join.from: false
    outworld_the_end:
      command.join.to: false
      command.join.from: false
    shard:
      permissions.build: true
      command.join.to: false
member:
  permissions:
    group.member: true
    permissions.build: true
    advancement.all: true
    command.sethome: true
    stargate.create.personal: true
    stargate.create.network: true
    stargate.create.network.galaxy: false
    stargate.create.gate: true
    stargate.destroy.personal: true
    stargate.option: true
    stargate.option.alwayson: false
    worldedit.help: true
    worldedit.calc: true
    worldedit.wand.toggle: true
    worldedit.selection.*: true
    worldguard.region.wand: true
    worldguard.region.claim: true
    worldguard.region.select.*: true
    worldguard.region.info: true
    worldguard.region.info.*: true
    worldguard.region.list: true
    worldguard.region.list.own: true
    worldguard.region.addowner.own.*: true
    worldguard.region.remove.own.*: true
    worldguard.region.setpriority.own.*: true
    worldguard.region.removemember.own.*: true
    worldguard.region.addmember.own.*: true
    worldguard.region.flag.regions.own.*: true
    worldguard.region.flag.flags.mob-spawning.*: true
    worldguard.region.flag.flags.snow-fall.*: true
    worldguard.region.flag.flags.snow-melt.*: true
    worldguard.region.flag.flags.frosted-ice-form.*: true
    worldguard.region.flag.flags.ice-form.*: true
    worldguard.region.flag.flags.ice-melt.*: true
    worldguard.region.flag.flags.use.*: true
    worldguard.region.flag.flags.chest-access.*: true
    worldguard.region.flag.flags.block-break.*: true
    worldguard.region.flag.flags.block-place.*: true
    worldguard.region.flag.flags.tnt.*: true
    bukkit.command.tps: true
    command.ride: true
    command.disguise: true
  worlds:
    world:
      livemap.markers: true
    world3:
      livemap.markers: true
    world4:
      livemap.markers: true
    omega:
      livemap.markers: true
    world_the_end:
      livemap.markers: true
    psi:
      livemap.markers: true
    shard:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      deadbolt.admin.bypass: true
      deadbolt.admin.snoop: true
      item.lighter: true
      advancement.all: false
    outworld:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      item.lighter: true
    outworld_nether:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      item.lighter: true
    outworld_the_end:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      item.lighter: true
    dev:
      command.fly: true
      stargate.create.personal: false
      stargate.create.network: false
      worldedit.navigation.jumpto.*: true
      worldedit.navigation.thru.*: true
      worldedit.setwand: true
      command.gm: true
      worldguard.region.flag.flags.other-explosion.*: true
      worldguard.region.flag.flags.ghast-fireball.*: true
      worldguard.region.flag.flags.spawn.*: true
      worldguard.region.flag.flags.teleport.*: true
      worldguard.region.flag.flags.invincible.*: true
      worldguard.region.claim: false
      command.items: true
      command.vanish: true
      advancement.all: false
      command.heal: true
      command.skipper: true
      command.skull: true
      command.kart: true
      minecraft.debugstick: true
    custom:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      advancement.all: false
      deadbolt.user.create.*: false
      command.ride: false
      command.disguise: false
    parkdev:
      advancement.all: false
  inheritance: default
regular:
  permissions:
    group.regular: true
    logblock.tools.tool: true
    worldguard.region.unlimited: true
    item.lighter: true
    command.approve: true
  worlds:
    dev:
      command.time: true
      command.playsound: true
      worldguard.region.claim: true
      command.text: true
      command.cb: true
  inheritance: member
donor:
  permissions:
    group.donor: true
  worlds:
    world:
      livemap.tracers: true
    world3:
      livemap.tracers: true
    world4:
      livemap.tracers: true
    omega:
      livemap.tracers: true
    world_the_end:
      livemap.tracers: true
    psi:
      livemap.tracers: true
  inheritance: regular
builder:
  permissions:
    group.builder: true
    command.sign: true
  worlds:
    parkdev:
      command.fly: true
      command.gm.others: true
      command.effect: true
      command.velocity: true
      command.heal.others: true
      command.entity: true
      command.cb: true
      command.cb.extended: true
      command.cloud: true
      command.acme: true
      command.goto: true
      command.bring: true
      command.put: true
      command.skull: true
      command.track: true
      worldedit.analysis.*: true
      worldedit.brush.*: true
      worldedit.clipboard.*: true
      worldedit.fast: true
      worldedit.perf: true
      worldedit.generation.*: true
      worldedit.global-mask: true
      worldedit.history.*: true
      worldedit.region.*: true
      worldedit.schematic.*: true
      worldedit.tool.*: true
      worldedit.setnbt: true
      worldedit.drawsel: true
      worldguard.region.claim: true
      minecraft.command.stopsound: true
    dev:
      command.gm.others: true
      command.effect: true
      command.velocity: true
      command.heal.others: true
      command.entity: true
      command.cb: true
      command.cb.extended: true
      command.cloud: true
      command.acme: true
      command.goto: true
      command.bring: true
      command.put: true
      command.skull: true
      command.track: true
      command.text: true
      worldedit.analysis.*: true
      worldedit.brush.*: true
      worldedit.clipboard.*: true
      worldedit.fast: true
      worldedit.perf: true
      worldedit.generation.*: true
      worldedit.global-mask: true
      worldedit.history.*: true
      worldedit.region.*: true
      worldedit.schematic.*: true
      worldedit.tool.*: true
      worldedit.setnbt: true
      worldedit.drawsel: true
      worldguard.region.claim: true
      minecraft.command.stopsound: true
    custom:
      command.arena: true
      command.acme: true
      command.fly: true
      command.gm: true
      command.effect: true
      command.velocity: true
      command.playsound: true
      command.time: true
      command.heal: true
      command.heal.others: true
      command.entity: true
      command.cb: true
      command.cb.extended: true
      command.items: true
      command.vanish: true
      command.cloud: true
      command.goto: true
      command.bring: true
      command.put: true
      command.skull: true
      command.track: true
      command.kart: true
      command.text: true
      worldedit.navigation.*: true
      worldguard.region.claim: true
      deadbolt.user.create.*: true
      minecraft.command.stopsound: true
      minecraft.debugstick: true
    world:
      livemap.tracers: true
    world3:
      livemap.tracers: true
    world4:
      livemap.tracers: true
    omega:
      livemap.tracers: true
    psi:
      livemap.tracers: true
  inheritance: regular
engineer:
  permissions:
    group.engineer: true
    worldedit.clipboard.copy: true
  worlds:
    dev:
      worldguard.region.*: true
      command.class: true
    custom:
      worldguard.region.*: true
      worldedit.analysis.*: true
      worldedit.brush.*: true
      worldedit.clipboard.*: true
      worldedit.fast: true
      worldedit.generation.*: true
      worldedit.global-mask: true
      worldedit.history.*: true
      worldedit.region.*: true
      worldedit.schematic.*: true
      worldedit.tool.*: true
      worldedit.light.*: true
      worldedit.setnbt: true
      worldedit.drawsel: true
      command.setwarp: true
      command.class: true
      command.arena.advanced: true
  inheritance: builder
moderator:
  permissions:
    group.moderator: true
    deadbolt.*: true
    deadbolt.broadcast.break: false
    deadbolt.broadcast.snoop: false
    worldguard.*: true
    worldguard.region.*: true
    logblock.lookup: true
    logblock.tp: true
    logblock.tools.toolblock: true
    OpenInv.openinv: true
    OpenInv.crossworld: true
    OpenInv.anychest: true
    OpenInv.editinv: true
    OpenInv.openender: true
    OpenInv.editender: true
    OpenInv.silent: true
    stargate.admin: true
    stargate.destroy: true
    worldedit.history.*: true
    worldedit.remove: true
    worldedit.extinguish: true
    worldedit.navigation.*: true
    worldedit.analysis.*: true
    worldedit.drawsel: true
    minecraft.command.toggledownfall: true
    minecraft.command.kick: true
    minecraft.command.playsound: true
    command.fly: true
    command.gm: true
    command.gm.others: true
    command.sign: true
    command.effect: true
    command.velocity: true
    command.playsound: true
    command.time: true
    command.entity: true
    command.sethome.others: true
    command.setwarp: true
    command.items: true
    command.vanish: true
    command.goto: true
    command.goto.anywhere: true
    command.mute: true
    command.text: true
    minecraft.nbt.place: true
    shop.admin: true
  worlds:
    dev:
      worldedit.*: true
    custom:
      worldedit.*: true
      logblock.tools.toolblock: false
    shard:
      logblock.tools.toolblock: false
  inheritance: engineer
admin:
  permissions:
    group.admin: true
    commandhelper.reloadaliases: true
    commandhelper.interpreter: true
    command.resettimes: true
  inheritance: moderator
