default:
    maxRoomHeight: 8
    chestCount: 1.2
    staggeredWall: true
floors:
    0:
        spawner: []
        trap: [chest_tnt]
        empty: lava
        wall: polished_blackstone_bricks
        column: polished_blackstone
        ceiling: polished_blackstone
        floor: [blackstone]
        utility: chiseled_polished_blackstone
        randomblocks: [soul_torch]
        edge: polished_blackstone_stairs
