default:
  tallDoors: true
  minRoomHeight: 5
  maxRoomHeight: 10
  lavaPit: 0.07
  waterPit: 0.07
  pit: 0.07
  minRoomSize: 6
  maxRoomSize: 21
  spawnerChance: 0.0
  spawnCount: 1
  extraDoorChance: 0.9
  empty: polished_andesite
  divider: polished_andesite
  wall: polished_andesite
  column: polished_andesite
  floor: polished_andesite
  ceiling: polished_andesite
  utility: [chiseled_stone_bricks]
  randomblocks: [gravel]
  edge: stone_brick_stairs
  doorFrame: polished_andesite
  overhead: 'lantern[hanging=true]'
  wallTorchChance: 0.07
  randomBlockChance: 0.08
  ascending: true
floors:
- roomTypes:
    stronghold:
      chance: 0.6
    deep_dark:
      chance: 0.2
    chasm:
      chance: 0.2
rooms:
  stronghold:
    divider: magma_block
    wall: [stone_bricks, stone_bricks, cracked_stone_bricks]
    floor: [stone_bricks, cracked_stone_bricks, mossy_stone_bricks]
    ceiling: [stone_bricks, stone_bricks, stone_bricks, cracked_stone_bricks]
  deep_dark:
    divider: sculk_catalyst
    wall: [sculk]
    column: sculk
    ceiling: sculk
    floor: [sculk]
    utility: [sculk_catalyst]
    randomblocks: [sculk, sculk, soul_torch]
    edge: sculk
    randomRoofHeight: true
    overhead: 'soul_lantern[hanging=true]'
    wallTorchChance: 0.0
    vine: twisting_vines_plant
    randomBlockChance: 0.2
  chasm:
    divider: air
    wall: 'light[level=6]'
    column: chain
    ceiling: netherite_block
    floor: [exposed_cut_copper, exposed_copper, 'exposed_cut_copper_slab[type=top]']
    utility: []
    edge: air
    lavaPit: 0.0
    waterPit: 0.0
    pit: 0.5
    wallTorchChance: 0.0
    randomBlockChance: 0.07
    randomblocks: [exposed_cut_copper, exposed_copper, exposed_cut_copper_slab]
