dungeonEntrance: true
default:
  maxRoomHeight: 9
  attic: 0.3
  balcony: 0.3
  lavaPit: 0.06
  extraDoorChance: 0.2
  maxRoomSize: 7
  spawnerChance: 0.8
floors:
- title: 'Stronghold'
  entranceDoor: true
  spawner: [skeleton, zombie, spider, silverfish]
  trap: [plate_potion_poison, plate_tnt, tripwire_arrow, static_web]
  wall: [stone_bricks, stone_bricks, stone_bricks, mossy_stone_bricks, cracked_stone_bricks, infested_cracked_stone_bricks]
  column: chiseled_stone_bricks
  ceiling: stone_bricks
  floor: [mossy_stone_bricks, mossy_stone_bricks, mossy_stone_bricks, stone_bricks, cracked_stone_bricks, infested_cracked_stone_bricks]
  utility: gravel
  randomblocks: [gravel]
  edge: stone_bricks
  door: oak_door
