default:
    chestCount: 0
    roof: false
floors:
    0:
        spawner: []
        wall: polished_andesite
        column: white_stained_glass
        floor: polished_andesite
        edge: air
        window: glass