member:
  permissions:
    group.member: true
    permissions.build: true
    command.sethome: true
    stargate.create.personal: true
    stargate.create.network: true
    stargate.create.network.galaxy: false
    stargate.create.gate: true
    stargate.destroy.personal: true
    stargate.option: true
    worldedit.help: true
    worldedit.wand.toggle: true
    worldedit.selection.*: true
    worldguard.region.wand: true
    worldguard.region.claim: true
    worldguard.region.select.*: true
    worldguard.region.info: true
    worldguard.region.info.*: true
    worldguard.region.list: true
    worldguard.region.list.own: true
    worldguard.region.addowner.own.*: true
    worldguard.region.remove.own.*: true
    worldguard.region.setpriority.own.*: true
    worldguard.region.removemember.own.*: true
    worldguard.region.addmember.own.*: true
    worldguard.region.flag.regions.own.*: true
    worldguard.region.flag.flags.mob-spawning.*: true
    worldguard.region.flag.flags.snow-fall.*: true
    worldguard.region.flag.flags.snow-melt.*: true
    worldguard.region.flag.flags.ice-form.*: true
    worldguard.region.flag.flags.ice-melt.*: true
    worldguard.region.flag.flags.use.*: true
    worldguard.region.flag.flags.chest-access.*: true
    worldguard.region.flag.flags.block-break.*: true
    worldguard.region.flag.flags.block-place.*: true
    worldguard.region.flag.flags.tnt.*: true
    bukkit.command.tps: true
    advancement.all: true
  worlds:
    world:
      livemap.markers: true
    world3:
      livemap.markers: true
    world4:
      livemap.markers: true
    omega:
      livemap.markers: true
    shard:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      deadbolt.admin.bypass: true
      deadbolt.admin.snoop: true
      build.wither: true
      PhysicalShop.admin: true
      build.wither: true
      item.lighter: true
      advancement.all: false
    outworld:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      build.wither: true
      item.lighter: true
    outworld_nether:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      build.wither: true
      item.lighter: true
    outworld_the_end:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      item.lighter: true
    dev:
      stargate.create.personal: false
      stargate.create.network: false
      worldedit.navigation.*: true
      command.gm: true
      worldguard.region.flag.flags.other-explosion.*: true
      worldguard.region.flag.flags.ghast-fireball.*: true
      worldguard.region.flag.flags.spawn.*: true
      worldguard.region.flag.flags.teleport.*: true
      worldguard.region.flag.flags.invincible.*: true
      worldguard.region.claim: false
      command.items: true
      command.vanish: true
      bl.getbanners: true
      advancement.all: false
      command.heal: true
    custom:
      stargate.create.personal: false
      stargate.create.network: false
      worldguard.region.claim: false
      command.sethome: false
      advancement.all: false
  inheritance: default
regular:
  permissions:
    group.regular: true
    logblock.tools.tool: true
    worldguard.region.unlimited: true
    item.lighter: true
    worldedit.calc: true
  worlds:
    dev:
      limitedworldedit: true
      fawe.worldguard: true
      command.time: true
      command.playsound: true
  inheritance: member
donor:
  permissions:
    group.donor: true
  worlds:
    world:
      livemap.tracers: true
    world3:
      livemap.tracers: true
    world4:
      livemap.tracers: true
    omega:
      livemap.tracers: true
  inheritance: regular
builder:
  permissions:
    group.builder: true
  worlds:
    dev:
      command.fly: true
      command.gm.others: true
      command.sign: true
      command.effect: true
      command.velocity: true
      command.explosion: true
      command.heal.others: true
      command.mob: true
      command.cb: true
      command.cloud: true
      limitedworldedit: true
      worldguard.region.claim: true
    custom:
      command.fly: true
      command.gm: true
      command.sign: true
      command.effect: true
      command.velocity: true
      command.playsound: true
      command.explosion: true
      command.time: true
      command.heal: true
      command.heal.others: true
      command.mob: true
      command.cb: true
      command.items: true
      command.vanish: true
      command.cloud: true
      worldedit.navigation.*: true
      worldguard.region.claim: true
      bl.getbanners: true
    world:
      livemap.tracers: true
    world3:
      livemap.tracers: true
    world4:
      livemap.tracers: true
    omega:
      livemap.tracers: true
  inheritance: regular
engineer:
  permissions:
    group.engineer: true
    worldedit.clipboard.copy: true
  worlds:
    dev:
      worldguard.region.*: true
      fawe.worldguard.member: true
    custom:
      worldguard.region.*: true
      fawe.worldguard: true
      fawe.worldguard.member: true
      limitedworldedit: true
  inheritance: builder
limitedworldedit:
  permissions:
    worldedit.brush.*: true
    worldedit.clipboard.*: true
    worldedit.fast: true
    worldedit.generation.*: true
    worldedit.global-mask: true
    worldedit.history.*: true
    worldedit.region.*: true
    worldedit.schematic.*: true
    worldedit.tool.*: true
moderator:
  permissions:
    group.moderator: true
    deadbolt.*: true
    worldguard.*: true
    logblock.lookup: true
    logblock.tp: true
    logblock.tools.toolblock: true
    deadbolt.broadcast.break: false
    deadbolt.broadcast.snoop: false
    OpenInv.openinv: true
    OpenInv.crossworld: true
    OpenInv.anychest: true
    OpenInv.editinv: true
    OpenInv.openender: true
    OpenInv.editender: true
    OpenInv.silent: true
    stargate.admin: true
    stargate.destroy: true
    redstoneclockdetector.*: true
    PhysicalShop.admin: true
    worldedit.history.*: true
    worldedit.butcher: true
    worldedit.remove: true
    worldedit.extinguish: true
    worldedit.navigation.*: true
    worldedit.analysis.*: true
    command.fly: true
    command.gm: true
    command.gm.others: true
    command.sign: true
    command.effect: true
    command.velocity: true
    command.playsound: true
    command.explosion: true
    command.time: true
    command.endercrystal: true
    command.mob: true
    command.sethome.others: true
    nocheat.admin: true
    minecraft.command.toggledownfall: true
    command.items: true
    command.vanish: true
  worlds:
    dev:
      worldedit.*: true
    custom:
      worldedit.*: true
      logblock.tools.toolblock: false
    shard:
      logblock.tools.toolblock: false
  inheritance: engineer
admin:
  permissions:
    group.admin: true
    commandhelper.reloadaliases: true
    commandhelper.interpreter: true
    command.resettimes: true
  inheritance: moderator
default:
  permissions:
    group.default: true
    permissions.build: false
    command.join.to: true
    command.join.from: true
  worlds:
    custom:
      permissions.build: true
      command.join.to: false
    outworld:
      command.join.to: false
      command.join.from: false
    outworld_nether:
      command.join.to: false
      command.join.from: false
    outworld_the_end:
      command.join.to: false
      command.join.from: false
    shard:
      permissions.build: true
      command.join.to: false
