title: 'Classic'
author: 'rivergod'
gear:
    0:
        name: DIAMOND_SWORD
        enchants:
            - elevel: 2
              etype: LOOT_BONUS_MOBS
    1:
        name: BOW
    2:
        name: ARROW
        qty: 20
    100:
        name: DIAMOND_BOOTS
    101:
        name: DIAMOND_LEGGINGS
    102:
        name: DIAMOND_CHESTPLATE
    103:
        name: DIAMOND_HELMET
waves:
    1:
        title: 'Proving Grounds'
        subtitle: 'Slimelings'
        mobs:
            - 'SLIME:1'
            - 'SLIME:1'
    2:
        subtitle: 'Dual Pierce'
        mobs:
            - SKELETON
            - SKELETON
    3:
        subtitle: 'The Horde'
        mobs:
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
    4:
        subtitle: 'Silken Terrors'
        mobs:
            - SPIDER
            - CAVESPIDER
    5:
        subtitle: 'Mama Slimer'
        mobs:
            - 'SLIME:4'
    6:
        subtitle: 'Mob Bandits'
        mobs:
            - ZOMBIE
            - ZOMBIE
            - SPIDER
            - SKELETON
    7:
        subtitle: 'Bone Brigade'
        mobs:
            - SKELETON
            - SKELETON
            - SKELETON
            - SKELETON
    8:
        subtitle: '*SSssss....*'
        mobs:
            - CREEPER
            - CREEPER
    9:
        subtitle: 'Cave Bandits'
        mobs:
            - 'SLIME:2'
            - 'SLIME:2'
            - SPIDER
            - SPIDER
            - CREEPER
    10:
        subtitle: 'Hidden Masters'
        mobs:
            - CREEPER
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
    11:
        subtitle: 'BOSS: Papa Slimer'
        mobs:
            - 'SLIME:8'
    12:
        title: 'Nether-Scape'
        subtitle: 'Bombos Bros.'
        mobs:
            - BLAZE
            - BLAZE
    13:
        subtitle: 'Lit Fuze'
        mobs:
            - BLAZE
            - CREEPER
            - CREEPER
            - CREEPER
    14:
        subtitle: 'Betrayal?'
        mobs:
            - 'WOLF:ANGRY'
            - 'WOLF:ANGRY'
            - 'WOLF:ANGRY'
    15:
        subtitle: 'The Juggernaut'
        mobs:
            - GHAST
    16:
        subtitle: 'Red Hot Marshmellows'
        mobs:
            - 'MAGMACUBE:4'
            - 'MAGMACUBE:4'
    17:
        subtitle: 'The Swarm'
        mobs:
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
    18:
        subtitle: 'Two-Worlds'
        mobs:
            - 'SLIME:2'
            - 'MAGMACUBE:2'
            - SPIDER
            - CAVESPIDER
            - ZOMBIE
            - 'PIGZOMBIE:400'
    19:
        subtitle: 'Big Bang'
        mobs:
            - CREEPER
            - CREEPER
            - GHAST
            - 'CREEPER:POWERED'
    20:
        subtitle: 'Porkcopolypse'
        mobs:
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
    21:
        subtitle: 'Hidden Power'
        mobs:
            - BLAZE
            - BLAZE
            - BLAZE
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - CREEPER
    22:
        subtitle: 'BOSS: Mega Magma'
        mobs:
            - 'MAGMACUBE:4'
            - 'MAGMACUBE:8'
    23:
        title: 'Throwback Town'
        subtitle: '1 Hit Wonders'
        mobs:
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - 'SLIME:4'
            - 'SLIME:4'
            - SKELETON
            - SKELETON
    24:
        subtitle: 'Electrifying'
        mobs:
            - 'CREEPER:POWERED'
            - 'CREEPER:POWERED'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
    25:
        subtitle: 'Poison Punch'
        mobs:
            - CAVESPIDER
            - CAVESPIDER
            - CAVESPIDER
            - SPIDER
            - SILVERFISH
            - SILVERFISH
    26:
        subtitle: 'Infection'
        mobs:
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - 'PIGZOMBIE:400'
            - CAVESPIDER
    27:
        subtitle: 'Nostalgia'
        mobs:
            - 'SLIME:1'
    28:
        subtitle: 'Slime Royalty'
        mobs:
            - 'SLIME:8'
            - 'MAGMACUBE:12'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
            - 'SLIME:1'
    29:
        subtitle: 'The Vanishing Thieves'
        mobs:
            - ENDERMAN
            - ENDERMAN
            - ENDERMAN
    30:
        subtitle: 'The Empowered Bandits'
        mobs:
            - BLAZE
            - BLAZE
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
            - 'CREEPER:POWERED'
    31:
        subtitle: 'The Thieves Guild'
        mobs:
            - ENDERMAN
            - ENDERMAN
            - ENDERMAN
            - ENDERMAN
            - ENDERMAN
            - SILVERFISH
            - SILVERFISH
            - SILVERFISH
    32:
        subtitle: "I'll Take 'Em All On!"
        mobs:
            - 'SLIME:4'
            - 'MAGMACUBE:4'
            - 'PIGZOMBIE:400'
            - 'WOLF:ANGRY'
            - CREEPER
            - SPIDER
            - CAVESPIDER
            - ZOMBIE
            - SKELETON
            - SILVERFISH
            - GHAST
            - ENDERMAN
            - BLAZE
    33:
        subtitle: 'BOSS: Rotten Behemoth'
        mobs:
            - GIANT
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
            - ZOMBIE
